# Contantes para estudo_dicom.py
IDENTIFICADOR_ESTABELECIMENTO_SAUDE_PADRAO = 1
ORIGEM_ESTUDO_DICOM = 'W'
SITUACAO = 'V'
SITUACAO_LAUDO = 'N'
NUMERO_EXAMES_HIS = 1
IDENTIFICADOR_PRIORIDADE_ESTUDO_DICOM = 'R'
SEXO_DEFAULT = 'O'
IMAGENS_DISPONIVEIS = False
MODALIDADE_PADRAO = 'OT'
