from api import db


class IntegracaoTasyModel(db.Model):
    __table_args__ = {"schema": "public"}
    __tablename__ = "integracao_tasy"

    identificador = db.Column(db.Integer, nullable=False, primary_key=True)
    nr_atendimento = db.Column(db.Integer, nullable=True)
    nr_prescricao = db.Column(db.Integer, nullable=True)
    nr_sequencia = db.Column(db.Integer, nullable=True)
    nr_seq_interno = db.Column(db.Integer, nullable=True)
    nr_acess_number = db.Column(db.Integer, nullable=True)
    cd_proced_tasy = db.Column(db.Integer, nullable=True)
    cd_proced_integracao = db.Column(db.Integer, nullable=True)
    cd_proced_tasy_lado = db.Column(db.Integer, nullable=True)
    ds_procedimento = db.Column(db.String, nullable=True)
    ie_lado = db.Column(db.String, nullable=True)
    ie_urgencia = db.Column(db.String, nullable=True)
    dt_prev_execucao = db.Column(db.DateTime, nullable=True)
    cd_setor_paciente = db.Column(db.Integer, nullable=True)
    cd_estabelecimento = db.Column(db.Integer, nullable=True)
    nm_pessoa_fisica = db.Column(db.String, nullable=True)
    dt_prescricao = db.Column(db.DateTime, nullable=True)
    dt_liberacao = db.Column(db.DateTime, nullable=True)
    cd_software_integracao = db.Column(db.Integer, nullable=True)
    cd_estab_terceiro = db.Column(db.Integer, nullable=True)
    cd_setor_execucao = db.Column(db.Integer, nullable=True)
    cd_paciente = db.Column(db.Integer, nullable=True)
    cd_prescritor = db.Column(db.Integer, nullable=True)
    ie_sexo = db.Column(db.String, nullable=True)
    dt_nascimento = db.Column(db.Date, nullable=True)
    cd_integracao_proc_interno = db.Column(db.Integer, nullable=True)
    qt_altura_cm = db.Column(db.Integer, nullable=True)
    qt_idade_pac = db.Column(db.Integer, nullable=True)
    qt_peso = db.Column(db.Integer, nullable=True)
    nr_crm_prescritor = db.Column(db.Integer, nullable=True)
    cd_modalidade_proc = db.Column(db.Integer, nullable=True)
    uf_crm_prescritor = db.Column(db.String, nullable=True)
    nr_cpf_paciente = db.Column(db.Integer, nullable=True)
    qt_prescrito = db.Column(db.Integer, nullable=True)
    nr_identidade_paciente = db.Column(db.String, nullable=True)
    nr_prontuario_paciente = db.Column(db.Integer, nullable=True)
    ds_endereco_paciente = db.Column(db.String, nullable=True)
    nr_endereco_paciente = db.Column(db.String, nullable=True)
    ds_bairro_paciente = db.Column(db.String, nullable=True)
    ds_municipio_paciente = db.Column(db.String, nullable=True)
    uf_paciente = db.Column(db.String, nullable=True)
    cd_cep_paciente = db.Column(db.Integer, nullable=True)
    nr_telefone_paciente = db.Column(db.String, nullable=True)
    cd_convenio = db.Column(db.Integer, nullable=True)
    ds_categoria_convenio = db.Column(db.String, nullable=True)
    ds_convenio = db.Column(db.String, nullable=True)
    cd_cgc = db.Column(db.Integer, nullable=True)
    nr_seq_motivo_atend = db.Column(db.Integer, nullable=True)
    ds_motivo_atend = db.Column(db.String, nullable=True)
    ds_motivo_suspensao = db.Column(db.String, nullable=True)
    cd_pessoa_fisica = db.Column(db.Integer, nullable=True)
    cd_procedimento = db.Column(db.Integer, nullable=True)
    cd_tipo_procedimento = db.Column(db.Integer, nullable=True)
    qt_procedimento = db.Column(db.Integer, nullable=True)
    dt_atualizacao = db.Column(db.DateTime, nullable=True)
    nm_usuario = db.Column(db.String, nullable=True)
    ds_observacao = db.Column(db.String, nullable=True)
    ie_origem_proced = db.Column(db.String, nullable=True)
    ds_dado_clinico = db.Column(db.String, nullable=True)
    ie_suspenso = db.Column(db.String, nullable=True)
    cd_setor_atendimento = db.Column(db.Integer, nullable=True)
    cd_medico = db.Column(db.Integer, nullable=True)
    dt_liberacao_medico = db.Column(db.DateTime, nullable=True)
    ie_recem_nato = db.Column(db.String, nullable=True)
    nm_paciente = db.Column(db.String, nullable=True)
    nr_cpf = db.Column(db.Integer, nullable=True)
    nr_prontuario = db.Column(db.Integer, nullable=True)
    nm_medico = db.Column(db.String, nullable=True)
    nr_crm = db.Column(db.Integer, nullable=True)
    cd_categoria = db.Column(db.Integer, nullable=True)
    cd_usuario_convenio = db.Column(db.Integer, nullable=True)
    cd_material_exame = db.Column(db.Integer, nullable=True)
    ds_material_especial = db.Column(db.String, nullable=True)
    ie_amostra_entregue = db.Column(db.String, nullable=True)
    ds_horarios = db.Column(db.String, nullable=True)
    nr_seq_exame = db.Column(db.Integer, nullable=True)
    ds_endereco = db.Column(db.String, nullable=True)
    nr_endereco = db.Column(db.Integer, nullable=True)
    ds_complemento = db.Column(db.String, nullable=True)
    ds_bairro = db.Column(db.String, nullable=True)
    ds_municipio = db.Column(db.String, nullable=True)
    sg_estado = db.Column(db.String, nullable=True)
    nr_telefone = db.Column(db.Integer, nullable=True)
    cd_cep = db.Column(db.String, nullable=True)
    ds_setor_paciente = db.Column(db.Integer, nullable=True)
    cd_unidade = db.Column(db.String, nullable=True)
    ie_executar_leito = db.Column(db.String, nullable=True)
    ds_modalidade = db.Column(db.String, nullable=True)
    na_accessionnumber = db.Column(db.Integer, nullable=True)
    ie_tipo_atendimento = db.Column(db.String, nullable=True)
    nr_seq_proc_interno = db.Column(db.Integer, nullable=True)
    cd_plano_convenio = db.Column(db.Integer, nullable=True)
    cd_plano = db.Column(db.Integer, nullable=True)
    cd_agenda = db.Column(db.Integer, nullable=True)
    ds_agenda = db.Column(db.String, nullable=True)
    cd_procedencia = db.Column(db.Integer, nullable=True)
    ds_procedencia = db.Column(db.String, nullable=True)
    cd_compl_conv = db.Column(db.Integer, nullable=True)
    dt_validade_carteira = db.Column(db.String, nullable=True)
    dt_resultado = db.Column(db.String, nullable=True)
    ds_senha = db.Column(db.String, nullable=True)
    nr_cpf_medico = db.Column(db.Integer, nullable=True)
    cd_estab_atend = db.Column(db.Integer, nullable=True)
    cd_estab_prescr = db.Column(db.Integer, nullable=True)
    dt_entrada = db.Column(db.DateTime, nullable=True)
    ds_tipo_atendimento = db.Column(db.String, nullable=True)
    ds_observacao_pf = db.Column(db.String, nullable=True)
    ds_unidade_atend = db.Column(db.String, nullable=True)
    ds_plano = db.Column(db.String, nullable=True)
    dt_admissao_hosp = db.Column(db.String, nullable=True)
    uf_medico = db.Column(db.String, nullable=True)
    ds_local = db.Column(db.String, nullable=True)
    ds_local_exec = db.Column(db.String, nullable=True)
    nm_medico_aten_ext = db.Column(db.String, nullable=True)
    crm_medico_aten_ext = db.Column(db.Integer, nullable=True)
    nm_social = db.Column(db.String, nullable=True)
    ds_email = db.Column(db.String, nullable=True)
    integrado_tasy = db.Column(db.Boolean, default=False)
    identificador_estudo_dicom = db.Column(
        db.Integer,
        db.ForeignKey("radius_taas.estudo_dicom.identificador"),
        nullable=True,
    )
    estudo_dicom = db.relationship(
        "EstudoDicomModel", back_populates="integracao_tasy")
    criado_worklist = db.Column(db.Boolean, default=False, nullable=False)
    laudo_enviado = db.Column(db.Boolean, default=False, nullable=False)
    exame_iniciado = db.Column(db.Boolean, default=False, nullable=False)
